# SPDX-License-Identifier: AGPL-3.0-only
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memory-manager.fullname" . }}
  labels:
    {{- include "memory-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "memory-manager.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
